theme: jekyll-theme-minimal
<!DOCTYPE html>
<html>
	<head>
		<title>Obianuju Ayalogu</title>
	</head>
	<body>
		<nav>
    		<ul>
        		<li><a href="/">Home</a></li>
	        	<li><a href="/About">About</a></li>
        		<li><a href="/cv">CV</a></li>
        		<li><a href="/blog">Blog</a></li>
    		</ul>
		</nav>
		<div class="container">
    		<div class="blurb">
        		<h1>Hi there, I'm Obianuju Ayalogu!</h1>
		
    		</div><!-- /.blurb -->
		</div><!-- /.container -->
		<footer>
    		<ul>
        		<li><a href="mailto:obianuju.ayalogu@gmail.com">email</a></li>
        		<li><a href="https://github.com/obianuju7">github.com/obianuju7</a></li>
			</ul>
		</footer>
	</body>
</html>
